"""
check_gastric_emptying_study.py

Quick diagnostic only - does NOT modify the cohort. Checks how many of the
existing K31.84 patients also have a gastric emptying study (GES) on
record, to help decide whether GES should be added as a corroborating
criterion in the main build script.

CPT codes for gastric emptying scintigraphy:
    78264  stomach only, <=4 hours
    78265  + small bowel transit, 24-26 hours
    78266  + small bowel and colon transit, multi-day

ASSUMES procedure.csv uses code_system == "CPT" - this was verified against
this specific dataset's standardized_terminology.csv and procedure.csv
header/sample rows (both confirmed "CPT" literally), so no need to re-check
unless this script gets reused on a different TriNetX pull later.

Run this AFTER build_gastroparesis_prokinetic_cohort.py. Writes a NEW file
rather than overwriting the original cohort CSV, so that re-running the
main build script later doesn't silently wipe out the GES columns added here.
"""

import subprocess
import pandas as pd

GCS_BASE = "gs://test-skynet-lh/joseph-sujka/trinetx-gastroparesis-dyspepsia"
PROCEDURE_FILE = f"{GCS_BASE}/procedure.csv"
COHORT_CSV = "gastroparesis_prokinetic_cohort.csv"
OUTPUT_CSV = "gastroparesis_prokinetic_cohort_with_GES.csv"

PROC_CODE_SYSTEM = "CPT"  # verified in this dataset
GES_CPT_CODES = {"78264", "78265", "78266"}

CHUNK_SIZE = 500_000


def stream_gcs_csv(gcs_path, usecols, chunksize=CHUNK_SIZE):
    proc = subprocess.Popen(["gsutil", "cat", gcs_path], stdout=subprocess.PIPE)
    reader = pd.read_csv(proc.stdout, usecols=usecols, dtype=str, chunksize=chunksize)
    for chunk in reader:
        yield chunk
    proc.stdout.close()
    proc.wait()


print(f"Scanning procedure.csv for GES CPT codes ({', '.join(sorted(GES_CPT_CODES))})...")

ges_first_date = {}   # patient_id -> earliest GES date (datetime or NaT)
ges_last_date = {}    # patient_id -> latest GES date (datetime or NaT)
ges_codes_seen = {}    # patient_id -> set of GES codes found

rows_seen = 0
for chunk in stream_gcs_csv(
    PROCEDURE_FILE,
    usecols=["patient_id", "code_system", "code", "date"],
):
    rows_seen += len(chunk)

    mask = (chunk["code_system"] == PROC_CODE_SYSTEM) & (chunk["code"].isin(GES_CPT_CODES))
    if not mask.any():
        continue

    hits = chunk.loc[mask, ["patient_id", "code", "date"]].copy()
    hits["date"] = pd.to_datetime(hits["date"], format="%Y%m%d", errors="coerce")

    for pid, sub in hits.groupby("patient_id"):
        ges_codes_seen.setdefault(pid, set()).update(sub["code"])
        min_date, max_date = sub["date"].min(), sub["date"].max()
        if pd.notna(min_date) and (pid not in ges_first_date or pd.isna(ges_first_date[pid]) or min_date < ges_first_date[pid]):
            ges_first_date[pid] = min_date
        if pd.notna(max_date) and (pid not in ges_last_date or pd.isna(ges_last_date[pid]) or max_date > ges_last_date[pid]):
            ges_last_date[pid] = max_date

print(f"  scanned {rows_seen:,} procedure rows")
print(f"  patients with any GES code, any year: {len(ges_first_date):,}")
for code in sorted(GES_CPT_CODES):
    count = sum(1 for codes in ges_codes_seen.values() if code in codes)
    print(f"    {code}: {count:,} patients")

if len(ges_first_date) == 0:
    print("\n  No matches at all - double check PROC_CODE_SYSTEM against the actual")
    print("  code_system value in procedure.csv before concluding GES isn't in this data.")

# ---------------------------------------------------------------------------
# Cross-reference against the existing K31.84 cohort
# ---------------------------------------------------------------------------

print(f"\nLoading {COHORT_CSV} to check overlap with the K31.84 cohort...")
cohort_df = pd.read_csv(COHORT_CSV, dtype={"patient_id": str})

if "in_study_period" not in cohort_df.columns:
    raise ValueError(
        f"{COHORT_CSV} is missing the expected 'in_study_period' column - "
        "was this generated by an older version of build_gastroparesis_prokinetic_cohort.py?"
    )

ges_patients = set(ges_first_date)
cohort_df["has_GES"] = cohort_df["patient_id"].isin(ges_patients)
cohort_df["first_GES_date"] = cohort_df["patient_id"].map(ges_first_date)
cohort_df["last_GES_date"] = cohort_df["patient_id"].map(ges_last_date)

# Parse first_K31_84_date back to datetime (it round-trips through CSV as a string)
first_k3184_dt = pd.to_datetime(cohort_df["first_K31_84_date"], errors="coerce")
first_ges_dt = pd.to_datetime(cohort_df["first_GES_date"], errors="coerce")
last_ges_dt = pd.to_datetime(cohort_df["last_GES_date"], errors="coerce")

# IMPORTANT: "before" and "after" are NOT symmetric checks against the same
# date. A patient with GES in 2019, dx in 2020, and another GES in 2022 truly
# had a GES both before AND after diagnosis - but if both checks used
# first_GES_date alone, the 2022 study would be invisible (first_GES_date is
# 2019, which is before dx, so an after-dx check on that same date would
# wrongly say False). So: "before" uses the EARLIEST GES (if even the
# earliest predates dx, that alone proves a pre-dx GES existed), while
# "after" uses the LATEST GES (if even the latest postdates dx, that alone
# proves a post-dx GES existed). Each direction needs its own anchor.
before_check_valid = first_k3184_dt.notna() & first_ges_dt.notna()  # both dates known for the "before" comparison
after_check_valid = first_k3184_dt.notna() & last_ges_dt.notna()    # both dates known for the "after" comparison

cohort_df["days_first_GES_to_K31_84"] = (first_k3184_dt - first_ges_dt).dt.days
cohort_df["days_last_GES_to_K31_84"] = (first_k3184_dt - last_ges_dt).dt.days

# When days_first_GES_to_K31_84 is NaN (one of the two dates missing), NaN > 0
# evaluates to False - that's correct behavior, not an accident, but it's also
# redundant with before_check_valid below, which makes the gate explicit rather
# than relying on that implicit NaN-comparison fallback.
cohort_df["GES_before_first_K31_84"] = before_check_valid & (cohort_df["days_first_GES_to_K31_84"] > 0)
cohort_df["GES_after_first_K31_84"] = after_check_valid & (cohort_df["days_last_GES_to_K31_84"] < 0)
# Same-day check still only looks at the earliest GES vs dx date - a patient
# could also have a later GES that happens to land on the dx date and this
# wouldn't catch it, but that's a rare enough edge case not worth the extra
# complexity of tracking every distinct GES date for this descriptive pass.
cohort_df["GES_same_day_as_first_K31_84"] = before_check_valid & (cohort_df["days_first_GES_to_K31_84"] == 0)

# Clinically, "GES before dx" and "GES same day as dx" both represent objective
# testing that was available at or before the time of diagnosis - the number
# Dr. Sujka will most likely want for "X% had objective gastric emptying
# testing supporting the diagnosis at the time it was made."
cohort_df["GES_before_or_same_day_K31_84"] = (
    cohort_df["GES_before_first_K31_84"] | cohort_df["GES_same_day_as_first_K31_84"]
)

both_ges_present = first_ges_dt.notna() & last_ges_dt.notna()
cohort_df["GES_repeated"] = both_ges_present & (last_ges_dt > first_ges_dt)
cohort_df["days_between_first_and_last_GES"] = (last_ges_dt - first_ges_dt).dt.days

# Cheap to add now since ges_codes_seen is already populated: lets you spot if
# one CPT code (e.g. 78264) is doing all the work, or patients have multiple.
# Named explicitly as "distinct CPT codes" since a patient with 78264 logged
# three times still gets a value of 1 here - this counts code variety, not
# raw procedure-record count.
ges_code_types = {pid: ",".join(sorted(codes)) for pid, codes in ges_codes_seen.items()}
cohort_df["GES_code_types"] = cohort_df["patient_id"].map(ges_code_types)
cohort_df["num_distinct_GES_CPT_codes"] = cohort_df["patient_id"].map(
    {pid: len(codes) for pid, codes in ges_codes_seen.items()}
).fillna(0).astype(int)

in_period = cohort_df["in_study_period"]
print("\nSANITY CHECK:")
print(f"  unique GES patients found in procedure.csv: {len(ges_first_date):,}")
print(f"  cohort size (all gastroparesis patients, any year): {len(cohort_df):,}")
print(f"  overlap rate (has_GES, full cohort): {cohort_df['has_GES'].mean() * 100:.2f}%")
print(f"\nOf the {in_period.sum():,} in-study-period K31.84 patients:")
print(f"  have a GES on record (any year): {(in_period & cohort_df['has_GES']).sum():,}")
print(f"  do NOT have a GES on record:     {(in_period & ~cohort_df['has_GES']).sum():,}")
print(f"  of those with a GES: {(in_period & cohort_df['GES_before_first_K31_84']).sum():,} ever had one before dx, "
      f"{(in_period & cohort_df['GES_after_first_K31_84']).sum():,} ever had one after dx, "
      f"{(in_period & cohort_df['GES_same_day_as_first_K31_84']).sum():,} earliest GES same day as dx")
print(f"  GES before or same day as dx (objective testing at/before diagnosis): "
      f"{(in_period & cohort_df['GES_before_or_same_day_K31_84']).sum():,}")
print(f"  GES repeated (more than one distinct date on record): {(in_period & cohort_df['GES_repeated']).sum():,}")

cohort_df.to_csv(OUTPUT_CSV, index=False)
print(f"\nWrote {OUTPUT_CSV} with has_GES, first_GES_date, last_GES_date,")
print("days_first_GES_to_K31_84, days_last_GES_to_K31_84, GES_before_first_K31_84,")
print("GES_after_first_K31_84, GES_same_day_as_first_K31_84, GES_before_or_same_day_K31_84,")
print("GES_repeated, days_between_first_and_last_GES, GES_code_types, and num_distinct_GES_CPT_codes columns added.")
print(f"(Original {COHORT_CSV} left untouched - use the new file as input to the next step.)")
print("(536.3-only patients currently show has_GES based on a GCS lookup keyed on patient_id,")
print(" but their first_GES_date isn't yet compared against their own 536.3 dx date - that's")
print(" the piece to add once you've confirmed with Dr. Sujka whether to anchor to 536.3.)")
print("\nThis is descriptive only - decide with Dr. Sujka whether/how to use GES")
print("(e.g. as an alternate corroboration alongside drug evidence, or a sensitivity analysis).")
